<?php
/**
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
echo "@font-face {
        font-family:'Red Hat Display';
        src:url(" . $block->getViewFileUrl('fonts/red-hat/red-hat-400.woff2') . ") format('woff2');
        font-weight:400;font-style:normal;font-display:swap;
    }
    @font-face {
        font-family:'Red Hat Display';
        src:url(" . $block->getViewFileUrl('fonts/red-hat/red-hat-600.woff2') . ") format('woff2');
        font-weight:600;font-style:normal;font-display:swap;
    }
    @font-face {
        font-family:'Red Hat Display';
        src:url(" . $block->getViewFileUrl('fonts/red-hat/red-hat-700.woff2') . ") format('woff2');
        font-weight:700;font-style:normal;font-display:swap;
    }
    body{font-family:'Red Hat Display','Helvetica Neue',Helvetica,Arial,sans-serif;}
";
