<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList\Item
 */
?>
<?php
$_post = $block->getPost();
$_postUrl = $block->escapeUrl($_post->getPostUrl());
$_postName = $block->escapeHtml($_post->getTitle());
?>
<li class="post-holder post-holder-<?= (int)$_post->getId() ?>">

    <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
    <?php if ($featuredImage) { ?>
        <?php
        $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
        if (!$featuredImgAlt) {
            $featuredImgAlt = $_postName;
        }
        ?>
        <div class="post-ftimg-hld">
            <a href="<?= /*@noEscape*/ $_postUrl ?>"
               title="<?= /*@noEscape*/ $_postName ?>">
                <img src="<?= $block->escapeUrl($featuredImage) ?>"
                     alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
            </a>
        </div>
    <?php } ?>

    <div class="post-info">
        <div class="post-date">
            <?= $block->escapeHtml($_post->getPublishDate('d-m-Y')) ?>
        </div>
        <h2 class="post-title">
            <a class="post-item-link"
               href="<?= /*@noEscape*/ $_postUrl ?>">
                <?= /*@noEscape*/ $_postName ?>
            </a>
        </h2>
    </div>
</li>