<script>window.document.title = "Azkarra - now it's maintenance time";</script>
<section>
    <article>
        <img class="logo" src="images/azkarra-logo.svg" width="" height="" />
        <h1>Azkarra is improving for you.<br>It'll take a while.</h1>
        <h2>Please try again in a moment.</h2>
        <p>or</p>
        <p>
            <a href="https://github.com/dev-jq/M2-AzkarraTheme-for-Core-Web-Vitals-and-SEO" target="_blank" rel="noopener noreferrer">
              <button style="background-color: #4CAF50; color: white; padding: 10px 20px; border: none; border-radius: 4px; font-size: 16px;">
                    View "Azkarra Theme" Repository on GitHub
              </button>
            </a>
        </p>
    </article>
</section>
