<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
    <title><?= $this->pageTitle ?></title>
    <base href="<?= $this->getViewFileUrl() ?>" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5.0">
    <meta name="robots" content="*"/>
    <link rel="stylesheet" href="css/styles.css" type="text/css" />
    <link rel="icon" href="images/favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
    <meta property="og:site_name" content="Azkarra - Magento 2 Theme"/>
    <meta property="og:url" content="https://m10393.app-on-demand.net/"/>
    <meta property="og:type" content="product_group"/>
    <meta property="og:title" content="[DEMO] Azkarra - M2 theme focused on PageSpeed Optimization and Core Web Vitals Performance | Magento 2 Theme by jqDev"/>
    <meta property="og:description" content="Magento 2 native theme focused on PageSpeed Optimization and Core Web Vitals Performance. This template is the best alternative for Magento Luma template."/>
    <meta property="og:image" content="images/default-logo-og.png"/>
    <meta property="og:image:width" content="600"/>
    <meta property="og:image:height" content="315"/>
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="[DEMO] Azkarra - M2 theme focused on PageSpeed Optimization and Core Web Vitals Performance | Magento 2 Theme by jqDev">
    <meta name="twitter:description" content="Magento 2 native theme focused on PageSpeed Optimization and Core Web Vitals Performance. This template is the best alternative for Magento Luma template.">
    <meta name="twitter:image" content="images/default-logo-og.png">    
</head>
<body>
    <main class="page-main">
        <?php require_once $contentTemplate; ?>
    </main>
</body>
</html>
